### ISSUE TITLE
Problemas com o 'hexdump' no esp32

### ISSUE THREAD

**Issue by WellingtonSouzaAbreu** [timum-viw/socket.io-client#97]
Erro: C:\Users\welli\Documents\Arduino\libraries\SocketIoClient\SocketIoClient.cpp: In member function 'void SocketIoClient::webSocketEvent(WStype_t, uint8_t*, size_t)':
C:\Users\welli\Documents\Arduino\libraries\SocketIoClient\SocketIoClient.cpp:40:27: error: 'hexdump' was not declared in this scope
    hexdump(payload, length);
Foram encontradas múltiplas bibliotecas para "WiFi.h"
Usado: C:\Users\welli\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.3\libraries\WiFi
Não usado: C:\Users\welli\Documents\Arduino\libraries\WiFiEspAT
Não usado: C:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
Erro compilando para a placa ESP32 Dev Module

**Comment by timum-viw** [comment]
please use the original library at https://github.com/Links2004/arduinoWebSockets. It supports a SocketIO Class.
Besides that I would like to inform you that I it is not very well received to just post an error dump and expect people to figure out what the problem is. A short 'hello' and a description of what you are trying to accomplish goes a long way. Hope you find a solution to your problem. cheers!
